AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Globals:
  Api:
    BinaryMediaTypes:
      - "*/*"

Resources:
  HtmlToPdfLambdaNative:
    Type: AWS::Serverless::Function
    Properties:
      ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/html-to-pdf-lambda:latest"
      PackageType: Image
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
    Metadata:
      Dockerfile: Dockerfile
      DockerTag: html-to-pdf-lambda
      DockerContext: ./
